name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        target-framework: ['net462', 'net48', 'net5.0', 'net9.0']
    
    steps:
    - uses: actions/checkout@v4
    # windows-lastest has .NET Framework pre-installed. No need to install it.
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Display .NET info
      run: dotnet --info
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Run Unit Tests
      run: dotnet test HttpMataki.NET.UnitTests/ --configuration Release --verbosity normal
      
    - name: Run Integration Tests - ${{ matrix.target-framework }}
      run: dotnet test HttpMataki.NET.IntegrationTests/ --configuration Release --framework ${{ matrix.target-framework }} --verbosity normal
      
    - name: Create NuGet Package - HttpMataki.NET
      run: dotnet pack HttpMataki.NET/HttpMataki.NET.csproj --configuration Release --output ./packages
      
    - name: Create NuGet Package - HttpMataki.NET.Auto
      run: dotnet pack HttpMataki.NET.Auto/HttpMataki.NET.Auto.csproj --configuration Release --output ./packages
      
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages-${{ matrix.target-framework }}
        path: ./packages/*.nupkg